name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: [windows-latest]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: make build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: wsl2host.exe
        # Directory containing files to upload
        path: wsl2host.exe

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          wsl2host.exe
